global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'smart-tg'
    environment: 'production'

scrape_configs:
  - job_name: "smart-tg-admin-backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["admin-backend:8000"]
    scrape_interval: 15s
    scrape_timeout: 10s

